version: "3.9"

services:
  app:
    image: ghcr.io/food-tech-ai/quickly-front-web:prod
    container_name: quickly-web
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_APP_NAME: Quickly
      NEXT_DISABLE_OPTIMIZED_IMAGES: "true"
    expose:
      - "3000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

networks:
  default:
    name: quickly-net
